// Typed accessor for the compiled corpus. The JSON is generated by
// scripts/build-corpus.mjs and never hand-edited (spec 01, rule zero).
import raw from '../../data/corpus_v3.json';
import type { Corpus } from './types';

export const corpus = raw as unknown as Corpus;
